# .github/labeler.yml
python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"

cpp:
  - changed-files:
      - any-glob-to-any-file: "**/*.cpp"
      - any-glob-to-any-file: "**/*.hpp"
      - any-glob-to-any-file: "**/*.h"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
      - any-glob-to-any-file: "docs/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "requirements*.txt"
      - any-glob-to-any-file: "pyproject.toml"
      - any-glob-to-any-file: "package.json"
      - any-glob-to-any-file: "CMakeLists.txt"
      - any-glob-to-any-file: "vcpkg.json"
      - any-glob-to-any-file: "conanfile*"
